/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#009eb9",
        "on-tertiary-fixed-variant": "#004e5c",
        "surface-bright": "#363943",
        "on-surface-variant": "#e8bcba",
        "primary-fixed-dim": "#ffb3b0",
        "on-tertiary": "#003640",
        "surface-container-highest": "#31353e",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-secondary": "#3f008e",
        "inverse-surface": "#e0e2ee",
        "background": "#03050c",
        "on-surface": "#e0e2ee",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-container-low": "#181b24",
        "primary-fixed": "#ffdad8",
        "error": "#ffb4ab",
        "surface": "#10131c",
        "on-primary": "#680010",
        "secondary": "#d2bbff",
        "outline-variant": "#5e3f3d",
        "surface-container-lowest": "#0b0e16",
        "outline-glow": "rgba(255, 26, 60, 0.15)",
        "outline": "#af8785",
        "on-primary-fixed-variant": "#92001b",
        "on-primary-container": "#5b000d",
        "surface-obsidian": "#03050c",
        "primary": "#ff1a3c",
        "on-secondary-fixed": "#25005a",
        "surface-glass-low": "rgba(8, 12, 28, 0.6)",
        "tertiary-fixed": "#acedff",
        "surface-tint": "#ff1a3c",
        "surface-variant": "#31353e",
        "on-secondary-container": "#c9aeff",
        "inverse-primary": "#bf0027",
        "on-error-container": "#ffdad6",
        "tertiary": "#4cd7f6",
        "primary-container": "#ff5359",
        "text-muted": "#94a3b8",
        "surface-dim": "#10131c",
        "on-tertiary-fixed": "#001f26",
        "surface-container-high": "#272a33",
        "text-on-surface": "#f8fafc",
        "inverse-on-surface": "#2d303a",
        "secondary-container": "#6001d1",
        "secondary-fixed-dim": "#d2bbff",
        "surface-container": "#1c1f28",
        "surface-glass-high": "rgba(12, 18, 43, 0.75)",
        "secondary-fixed": "#eaddff",
        "on-background": "#e0e2ee",
        "on-primary-fixed": "#410007",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-tertiary-container": "#002f38",
        "neon-red": "#ff1a3c",
        "accent-red": "#ff1a3c",
        "accent-red-hover": "#ff4d6a",
      },
      borderRadius: {
        "DEFAULT": "12px",
        "lg": "24px",
        "xl": "32px",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "24px",
        "md": "16px",
        "xs": "4px",
        "xl": "36px",
        "sm": "8px",
        "base": "4px",
        "margin-desktop": "48px",
        "lg": "24px"
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Outfit", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
      }
    },
  },
  plugins: [],
}
